---
apiVersion: v1
kind: ConfigMap

metadata:
    name: shared-web-env

data:
    PORT: "8081"
    SERVICE_CHECK_URL: http://dev.sweetrpg.com/health/ping
    HEALTH_CHECK_URL: http://dev.sweetrpg.com/health/status
    APPLICATION_BASE_PATH: ""
    LIBRARY_API_BASE_URL: ""
