---
apiVersion: v1
kind: ConfigMap

metadata:
    name: web-env

data:
    PORT: "8081"
    APPLICATION_BASE_PATH: "/shared"
    BUILD_INFO_PATH: /app/build-info.json
    ASSETS_URL: https://dev.sweetrpg.com/assets
