---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-support

resources:
    - namespace.yaml
    - ../../base
    - configmaps.yaml
    - destination-rules.yaml
patchesStrategicMerge:
    - replicas.yaml

commonLabels:
    app: shared-web
    version: v1
    platform: sweetrpg
    package: shared
    component: web

generatorOptions:
    disableNameSuffixHash: true
