---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-shared

resources:
    - ../../base
    - configmaps.yaml
    - ingress.yaml
    - middlewares/errors.yaml
    - middlewares/strip.yaml
    - pod-monitor.yaml
    - secrets/auth.yaml
    - secrets/cache.yaml
    - secrets/files.yaml
    - secrets/misc.yaml

labels:
    - pairs:
        app: web
        version: v1
        platform: sweetrpg
        package: shared
        component: web

generatorOptions:
    disableNameSuffixHash: true

images:
  - name: shared-web
    newName: ghcr.io/sweetrpg/shared-web
    newTag: latest
