---
apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
    name: shared-web-v1

spec:
    minAvailable: 1
    selector:
        matchLabels:
            platform: sweetrpg
            app: shared-web
            component: web
            package: shared
            version: v1
