---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor

metadata:
    name: sweetrpg-shared-web
    labels:
        release: prometheus

spec:
    namespaceSelector:
        matchNames:
            - sweetrpg-shared
    podMetricsEndpoints:
        - port: http
    selector:
        matchLabels:
            app: web
            platform: sweetrpg
            package: shared
            component: web
