---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret

metadata:
    name: shared-web-auth
    namespace: sweetrpg-support

spec:
    externalSecretName: shared-web-auth

    namespaceSelector:
        matchLabels:
            name: sweetrpg-support

    refreshTime: 1m

    externalSecretSpec:
        refreshInterval: "1h"
        secretStoreRef:
            name: akeyless
            kind: ClusterSecretStore
        target:
            name: shared-web-auth
            creationPolicy: Owner
        dataFrom:
            - extract:
                  key: Auth0

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret

metadata:
    name: shared-web-misc
    namespace: sweetrpg-support

spec:
    externalSecretName: shared-web-misc

    namespaceSelector:
        matchLabels:
            name: sweetrpg-support

    refreshTime: 1m

    externalSecretSpec:
        refreshInterval: 1h
        secretStoreRef:
            name: akeyless
            kind: ClusterSecretStore
        target:
            name: shared-web-misc
            creationPolicy: Owner
        dataFrom:
            - extract:
                  key: /sweetrpg/support/assets/web/misc

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret

metadata:
    name: shared-web-cache
    namespace: sweetrpg-support

spec:
    externalSecretName: shared-web-cache

    namespaceSelector:
        matchLabels:
            name: sweetrpg-support

    refreshTime: 1m

    externalSecretSpec:
        refreshInterval: 1h
        secretStoreRef:
            name: akeyless
            kind: ClusterSecretStore
        target:
            name: shared-web-cache
            creationPolicy: Owner
        dataFrom:
            - extract:
                  key: /sweetrpg/support/cache/client

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret

metadata:
    name: shared-web-files
    namespace: sweetrpg-support

spec:
    externalSecretName: shared-web-files

    namespaceSelector:
        matchLabels:
            name: sweetrpg-support

    refreshTime: 1m

    externalSecretSpec:
        refreshInterval: 1h
        secretStoreRef:
            name: akeyless
            kind: ClusterSecretStore
        target:
            name: shared-web-files
            creationPolicy: Owner
            template:
                type: Opaque
                data:
                    newrelic.ini: "{{ .contents | toString }}"
        data:
            - secretKey: contents
              remoteRef:
                  key: NewRelic
