---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
    name: shared-web-files

spec:
    refreshInterval: 1h
    secretStoreRef:
        name: akeyless
        kind: ClusterSecretStore
    target:
        name: web-files
        creationPolicy: Owner
        template:
            type: Opaque
            data:
                newrelic.ini: "{{ .contents | toString }}"
    data:
        - secretKey: contents
          remoteRef:
              key: NewRelic
