---
apiVersion: v1
kind: ConfigMap

metadata:
    name: shared-web-common

data:
    FLASK_PORT: "8081"
    FLASK_APP: sweetrpg_shared_web.application.main:create_app
    FLASK_ENV: production
    NEW_RELIC_CONFIG_FILE: /config/newrelic.ini
    REDIS_PORT: "6379"
