---
apiVersion: apps/v1
kind: Deployment

metadata:
    name: web-v1

spec:
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        type: RollingUpdate
    selector:
        matchLabels:
            platform: sweetrpg
            app: web
            component: web
            package: shared
            version: v1
    template:
        metadata:
            labels:
                platform: sweetrpg
                app: web
                component: web
                package: shared
                version: v1
            annotations:
                reloader.stakater.com/auto: "true"
                openfeature.dev/enabled: "true"
                openfeature.dev/featureflagsource: "sweetrpg-system/shared-web"
        spec:
            serviceAccountName: web
            imagePullSecrets:
                - name: sweetrpg-registry
            containers:
                - name: app
                  image: shared-web
                  imagePullPolicy: Always
                  envFrom:
                      - configMapRef:
                            name: web-common
                      - configMapRef:
                            name: web-env
                      - secretRef:
                            name: web-misc
                      - secretRef:
                            name: web-cache
                  env: []
                  ports:
                      - containerPort: 8081
                        name: http
                  resources:
                      requests:
                          cpu: "20m"
                          memory: "55Mi"
                      limits:
                          cpu: "1"
                          memory: "1Gi"
                  livenessProbe:
                    httpGet:
                        path: /health/ping
                        port: 8081
                    initialDelaySeconds: 90
                    timeoutSeconds: 10
                  readinessProbe:
                    httpGet:
                        path: /health/ping
                        port: 8081
                    initialDelaySeconds: 30
                    timeoutSeconds: 10
                  volumeMounts:
                      - mountPath: /data
                        name: data
            volumes:
                - name: data
                  emptyDir: {}
            restartPolicy: Always
