---
kind: Service
apiVersion: v1

metadata:
    name: shared-web-v1

spec:
    selector:
        platform: sweetrpg
        app: sweetrpg-shared-web-v1
        component: web
        package: shared
        version: v1
    type: LoadBalancer
    ports:
        - name: http
          port: 8081
          targetPort: http
