---
kind: Service
apiVersion: v1

metadata:
    name: shared-web

spec:
    selector:
        app: shared
        component: web
        platform: sweetrpg
    type: LoadBalancer
    ports:
        - name: http
          port: 8081
          targetPort: http
