---
apiVersion: v1
kind: ConfigMap

metadata:
    name: web-env

data:
    PORT: "8081"
    APPLICATION_BASE_PATH: "/shared"
    BUILD_INFO_PATH: /app/build-info.json
    ASSETS_URL: https://sweetrpg.local/assets
    # OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo-distributor.observability.svc.cluster.local:4318
    LOG_LEVEL: INFO
