---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-shared

resources:
    - ../../base
    - configmaps.yaml
    - ingress.yaml
    - middlewares/errors.yaml
    - middlewares/strip.yaml
    - secrets/auth.yaml
    - secrets/cache.yaml
    - secrets/files.yaml
    - secrets/misc.yaml

labels:
    - pairs:
        app.kubernetes.io/name: shared-web
        app.kubernetes.io/version: v1
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: shared
        com.sweetrpg/env: local
      includeSelectors: false
      includeTemplates: true

generatorOptions:
    disableNameSuffixHash: true

images:
  - name: shared-web
    newName: ghcr.io/sweetrpg/shared-web
    newTag: latest
